version: '3'
services:
  web:
    image: templateaula10:latest
    container_name: 'TemplateAula10'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    tty: true
    networks:
      - template-aula-net

networks:
  template-aula-net:
    name: template-aula-net
    driver: bridge
